BankingCircle_EUR_Withdrawal
FreemarketFX/BankingIntegrationTests pull request #1
Opened 2024-01-29 09:34 UTC by jhansi-freemarket

Added e2e flow for EUR withdrawal and payment for Banking Circle Integration

2024-01-29 10:07 UTC, Jonny-Freemarket requested changes
Looks good, just some QOL changes.

2024-01-29 10:07 UTC, Jonny-Freemarket commented on BankingIntegrationTests/UI/Functions/Cashflows.cs
> +            UtilClass.WaitABit(50000);
Is there anyway these aren't arbitrary waits? 50 seconds is a long time for a test to wait.

Maybe by combining the later steps where it does the search with a poll if the search doesn't result in anything? We know Cashflows are slow to appear, so even a 5 second wait between pols would be okay, but arbitrary wait really should be avoided.

2024-01-29 10:07 UTC, Jonny-Freemarket commented on BankingIntegrationTests/UI/Functions/ProcessPayment.cs
> +            UtilClass.WaitABit(30000);
Blah blah arbitrary wait

2024-01-29 10:07 UTC, Jonny-Freemarket commented on BankingIntegrationTests/UI/Functions/ProcessPayment.cs
> +                    Console.WriteLine("Either transaction not found or there is nothing to approve!!");
Does `Console.WriteLine(..)` work? Just thinking in xunit it doesn't and you have to use their `ITestOutputHelper`.

2024-01-29 12:29 UTC, jhansi-freemarket commented on BankingIntegrationTests/Feature/BankingCircle/BankingCirclePaymentsHappyPath.cs
> +        var endToEndId = paymentNumber;
Sure, will merge these steps into a single method

2024-01-29 13:03 UTC, jhansi-freemarket commented on BankingIntegrationTests/UI/Functions/ProcessPayment.cs
> +                    Console.WriteLine("Either transaction not found or there is nothing to approve!!");
No, this does not work.. I forgot to change it to ITestOutputHelper.

2024-01-29 15:59 UTC, jhansi-freemarket commented on BankingIntegrationTests/UI/Functions/Cashflows.cs
> +            UtilClass.WaitABit(50000);
Removed this wait. It's not needed here.

2024-01-30 08:56 UTC, jhansi-freemarket commented on BankingIntegrationTests/Feature/BankingCircle/BankingCirclePaymentsHappyPath.cs
> +        .Excluding(pse => pse.InstructedTransactionId)
Done.. added assertion for InstructedTransactionId

2024-01-31 14:46 UTC, Elizabeth-Freemarket commented on BankingIntegrationTests/Feature/ClearBank/PaymentsHappyPath.cs
> +        UtilClass.WaitABit(20000);
I am facing this issue too with mine.. thanks for the tip @jhansi-freemarket

2024-01-31 14:49 UTC, Jonny-Freemarket commented on BankingIntegrationTests/Feature/ClearBank/PaymentsHappyPath.cs
> +        UtilClass.WaitABit(20000);
We should never have any arbitrary waits ever for anything, but I don't know enough about Playwright to suggest a way forward so this will have to do for now.

2024-01-31 14:51 UTC, jhansi-freemarket commented on BankingIntegrationTests/Feature/ClearBank/PaymentsHappyPath.cs
> +        UtilClass.WaitABit(20000);
ah I missed updating this on CB test :-) Shall I update it? or leave it with you @Elizabeth-Freemarket

2024-02-01 10:20 UTC, Jonny-Freemarket approved these changes
LGTM

2024-02-01 10:23 UTC, merged